name: Auto Merge Dependabot PRs

on:
  pull_request:
    branches:
      - main
    types: [ opened, synchronize ]

jobs:
  auto-merge-dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Auto Merge if Dependabot PR meets criteria
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          VERSION_LABEL=$(gh pr view $PR_NUMBER --json labels --jq '.labels[].name' | grep -E 'dependencies|version:patch|version:minor')
          if [[ "$VERSION_LABEL" != "" && "$(gh pr checks $PR_NUMBER --json conclusion --jq '.checkRuns[].conclusion')" == "success" ]]; then
            gh pr merge $PR_NUMBER --merge
            echo "Merged PR #$PR_NUMBER"
          else
            echo "PR #$PR_NUMBER did not meet criteria for merging."
          fi
